server:
  port: 5000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BOOKING-SERVICE
          uri:
            "lb://BOOKING-SERVICE"
          predicates:
            - Path=/api/bookings/**
        - id: CATEGORY-SERVICE
          uri:
            "lb://CATEGORY-SERVICE"
          predicates:
            - Path=/api/categories/**
        - id: PAYMENT-SERVICE
          uri:
            "lb://PAYMENT-SERVICE"
          predicates:
            - Path=/api/payments/**
        - id: SALON-SERVICE
          uri:
            "lb://SALON-SERVICE"
          predicates:
            - Path=/api/salons/**
        - id: SERVICE-OFFERING
          uri:
            "lb://SERVICE-OFFERING"
          predicates:
            - Path=/api/service-offering/**
        - id: USER-SERVICE
          uri:
            "lb://USER-SERVICE"
          predicates:
            - Path=/api/users/**, /api/auth/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka
