services:
  user_service_db:
    image: mysql
    container_name: user_service_db
    ports:
      - 3301:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
    networks:
      - sh32bit

  salon_service_db:
    image: mysql
    container_name: salon_service_db
    ports:
      - 3302:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salon_service_db
    networks:
      - sh32bit

  booking_service_db:
    image: mysql
    container_name: booking_service_db
    ports:
      - 3303:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking_service_db
    networks:
      - sh32bit

  category_service_db:
    image: mysql
    container_name: category_service_db
    ports:
      - 3304:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: category_service_db
    networks:
      - sh32bit

  payment_service_db:
    image: mysql
    container_name: payment_service_db
    ports:
      - 3305:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_service_db
    networks:
      - sh32bit

  service_offering_db:
    image: mysql
    container_name: service_offering_db
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service_offering_db
    networks:
      - sh32bit

  eureka-server:
    image: "shakhabkhan/eureka-server:v1"
    container_name: eureka-server
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8070/actuator/health | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sh32bit

  user-service:
    image: "shakhabkhan/user-service:v1"
    container_name: user-service
    ports:
      - "5001:5001"
    depends_on:
      user_service_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent user-service:5001/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "user-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://user_service_db:3306/user_service_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sh32bit

  salon-service:
    image: "shakhabkhan/salon-service:v1"
    container_name: salon-service
    ports:
      - "5002:5002"
    depends_on:
      salon_service_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent salon-service:5002/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "salon-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salon_service_db:3306/salon_service_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sh32bit

  category-service:
    image: "shakhabkhan/category-service:v1"
    container_name: category-service
    ports:
      - "5003:5003"
    depends_on:
      category_service_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent category-service:5003/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "category-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://category_service_db:3306/category_service_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sh32bit

  service-offering:
    image: "shakhabkhan/service-offering:v1"
    container_name: service-offering
    ports:
      - "5004:5004"
    depends_on:
      service_offering_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent service-offering:5004/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "service-offering"
      SPRING_DATASOURCE_URL: "jdbc:mysql://service_offering_db:3306/service_offering_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sh32bit

  booking-service:
    image: "shakhabkhan/booking-service:v1"
    container_name: booking-service
    ports:
      - "5005:5005"
    depends_on:
      booking_service_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent booking-service:5005/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "booking-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://booking_service_db:3306/booking_service_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sh32bit

  payment-service:
    image: "shakhabkhan/payment-service:v1"
    container_name: payment-service
    ports:
      - "5006:5006"
    depends_on:
      payment_service_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent payment-service:5006/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "payment-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://payment_service_db:3306/payment_service_db"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sh32bit

  gateway-server:
    image: "shakhabkhan/gateway-server:v1"
    container_name: gateway-server
    ports:
      - "5000:5000"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent gateway-server:5000/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sh32bit

networks:
  sh32bit:
    driver: "bridge"
